package eu.comvantage.cw7_IAF_List_Of_Orders;

import java.util.ArrayList;
import eu.comvantage.cw7_IAF_List_Of_Orders.R;

public final class DataGenerator {
	private static Order o;
	
    public static ArrayList<Order> getDummyData(){
    	ArrayList<Order> orders = new ArrayList<Order>();
    	
    	String currentDate = "20140801";
    	String clients[] = {"Peter Novak", "Conny Weber", "Arnold Jager", "John Doe", "Steffan Baum" , "Marjan Leber", "Susanne Millner", "Marlies Narat","Conny Weber","Sissi Jarz","Stephen Longal","Bud Spencer","Martin Opetik","Oliver Rudolfs","Katharina Ilster"};
    	String processor[] = {"Post AG", "Sportshirts AG", "ProShirt d.o.o.", "DHL", "StickIt d.o.o.", "Fuchs GmbH"};
    	FactSheet demosheet = new FactSheet();
    	demosheet.setDescription("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.");
    	Task demotask1 = new Task();
    	demotask1.setTaskcode(0);
    	demotask1.setTaskdescription("New");
    	Task demotask6 = new Task();
    	demotask6.setTaskcode(1);
    	demotask6.setTaskdescription("Production of Parts");
    	Task demotask4 = new Task();
    	demotask4.setTaskcode(2);
    	demotask4.setTaskdescription("Delivery to Embroidery");
    	Task demotask5 = new Task();
    	demotask5.setTaskcode(3);
    	demotask5.setTaskdescription("Embroidering Parts");
    	Task demotask2 = new Task();
    	demotask2.setTaskcode(4);
    	demotask2.setTaskdescription("Assembly of Shirt");
    	Task demotask3 = new Task();
    	demotask3.setTaskcode(5);
    	demotask3.setTaskdescription("Delivery to Customer");
    	Task demotask7 = new Task();
    	demotask7.setTaskcode(6);
    	demotask7.setTaskdescription("Completed");
    	
    	
    	o = new Order();
    	o.setId("2014111001");
    	o.setClient(clients[0]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(0);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask1);
    	o.setShirtimage(R.drawable.shirt1);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("First Generation Black / Red");
    	o.setOrderdate("20.08.2014");
    	o.setDelivered("25.08.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId("2014111002");
    	o.setClient(clients[0]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(0);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask1);
    	o.setShirtimage(R.drawable.shirt2);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Individual Design White / Green");
    	o.setOrderdate("20.08.2014");
    	o.setDelivered("25.08.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"03");
    	o.setClient(clients[2]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask6);
    	o.setShirtimage(R.drawable.shirt3);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[4]);
    	o.setShirttype("White / Yellow");
    	o.setOrderdate("02.10.2014");
    	o.setDelivered("04.10.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"04");
    	o.setClient(clients[3]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask6);
    	o.setShirtimage(R.drawable.shirt4);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("First Gen. White / Black");
    	o.setOrderdate("01.10.2014");
    	o.setDelivered("03.10.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"05");
    	o.setClient(clients[4]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt5);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Special Edition Black");
    	o.setOrderdate("18.09.2014");
    	o.setDelivered("21.09.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"06");
    	o.setClient(clients[5]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask3);
    	o.setShirtimage(R.drawable.shirt6);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Special Edition B/W");
    	o.setOrderdate("10.09.2014");
    	o.setDelivered("15.09.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"07");
    	o.setClient(clients[4]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask4);
    	o.setShirtimage(R.drawable.shirt7);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Special Edition");
    	o.setOrderdate("01.08.2014");
    	o.setDelivered("10.08.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"08");
    	o.setClient(clients[7]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask5);
    	o.setShirtimage(R.drawable.shirt8);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[4]);
    	o.setShirttype("First Generation");
    	o.setOrderdate("01.08.2014");
    	o.setDelivered("09.08.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"09");
    	o.setClient(clients[8]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask5);
    	o.setShirtimage(R.drawable.shirt9);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("SAP Research");
    	o.setOrderdate("22.07.2014");
    	o.setDelivered("30.07.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"10");
    	o.setClient(clients[9]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt1);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Special Edition");
    	o.setOrderdate("13.07.2014");
    	o.setDelivered("16.07.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"11");
    	o.setClient(clients[10]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask7);
    	o.setShirtimage(R.drawable.shirt2);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("First Generation");
    	o.setOrderdate("13.07.2014");
    	o.setDelivered("18.07.2014");
    	orders.add(o);
    	
    	/*
    	o = new Order();
    	o.setId(currentDate+"12");
    	o.setClient(clients[11]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(5);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask3);
    	o.setShirtimage(R.drawable.shirt7);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Special Edition");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"13");
    	o.setClient(clients[12]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(5);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt8);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("First Generation");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"14");
    	o.setClient(clients[13]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(5);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt5);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Special Edition Black");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"15");
    	o.setClient(clients[14]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(5);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt6);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("First Generation");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"16");
    	o.setClient(clients[9]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(4);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt3);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("First Generation");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"17");
    	o.setClient(clients[1]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(4);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt4);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Special Edition");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"18");
    	o.setClient(clients[2]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(4);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt9);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("First Generation");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"19");
    	o.setClient(clients[5]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(4);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask2);
    	o.setShirtimage(R.drawable.shirt3);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[2]);
    	o.setShirttype("Special Edition");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"20");
    	o.setClient(clients[7]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(5);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask3);
    	o.setShirtimage(R.drawable.shirt5);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[3]);
    	o.setShirttype("First Generation");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"21");
    	o.setClient(clients[4]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(5);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask3);
    	o.setShirtimage(R.drawable.shirt6);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[0]);
    	o.setShirttype("Special Edition");
    	o.setOrderdate("22.05.2014");
    	o.setDelivered("30.05.2014");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"22");
    	o.setClient(clients[0]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask7);
    	o.setShirtimage(R.drawable.shirt1);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[3]);
    	o.setShirttype("First Generation");
    	o.setOrderdate("07.08.2014");
    	o.setDelivered("11.08.2014");
    	o.setDuration("4 days");
    	o.setPayment("08.08.2012, Transaction");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"23");
    	o.setClient(clients[1]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask7);
    	o.setShirtimage(R.drawable.shirt2);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[3]);
    	o.setShirttype("First Generation Black");
    	o.setOrderdate("05.08.2014");
    	o.setDelivered("10.08.2014");
    	o.setDuration("5 days");
    	o.setPayment("10.08.2014, At Delivery");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"24");
    	o.setClient(clients[2]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask7);
    	o.setShirtimage(R.drawable.shirt3);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[0]);
    	o.setShirttype("White / Yellow");
    	o.setOrderdate("04.08.2014");
    	o.setDelivered("10.8.2014");
    	o.setDuration("6 days");
    	o.setPayment("05.08.2014, Transaction");
    	orders.add(o);
    	
    	o = new Order();
    	o.setId(currentDate+"25");
    	o.setClient(clients[5]);
    	o.setFactsheet(demosheet);
    	o.setStatuscode(6);
    	o.setStatuscheckinout(0);
    	o.setTask(demotask7);
    	o.setShirtimage(R.drawable.shirt3);
    	o.setLogoimage(R.drawable.ic_launcher);
    	o.setProcessor(processor[0]);
    	o.setShirttype("White / Yellow");
    	o.setOrderdate("12.08.2014");
    	o.setDelivered("15.08.2014");
    	o.setDuration("3 days");
    	o.setPayment("15.08.2014, At Delivery");
    	orders.add(o);
    	*/
    	return orders;
    }
}